#!/bin/bash

prev=($(grep '^cpu ' /proc/stat))
sleep 1
curr=($(grep '^cpu ' /proc/stat))

prev_idle=${prev[4]}
curr_idle=${curr[4]}

prev_total=0
curr_total=0
for i in "${prev[@]:1}"; do ((prev_total += i)); done
for i in "${curr[@]:1}"; do ((curr_total += i)); done

total_diff=$((curr_total - prev_total))
idle_diff=$((curr_idle - prev_idle))
cpu_usage=$((100 * (total_diff - idle_diff) / total_diff))

if [ "$cpu_usage" -le 50 ]; then
  exit 33
fi

echo "{\"full_text\": \"CPU ${cpu_usage}%\", \"color\": \"#FF0000\"}"
