#!/bin/bash

mount_point="/"
avail=$(df -h "$mount_point" | awk 'NR==2 { print $4 }')
avail_pct=$(df -h "$mount_point" | awk 'NR==2 { sub("%", "", $(NF-1)); print $(NF-1) }')

if [ "$avail_pct" -ge 10 ]; then
  exit 33
fi

echo "{\"full_text\": \"DISK $avail free\", \"color\": \"#FF0000\"}"
