#!/bin/bash

# You might need to adjust this grep target depending on your sensors output
temp=$(sensors | grep -m 1 'Package id 0:' | awk '{gsub("+", "", $3); gsub("°C", "", $3); print int($3)}')

if [ "$temp" -lt 75 ]; then
  exit 33
fi

echo "{\"full_text\": \"TEMP ${temp}°C\", \"color\": \"#FF0000\"}"
